task: S2G
data:
  input_data: videos
  input_streams:
    - keypoint
    - rgb
  keypoint_file: ../../data/phoenix2014/keypoints_hrnet_dark_coco_wholebody.pkl
  use_keypoints:
    - pose
    - mouth_half
    - hand
    - face_others_1_3
  zip_file: ../../data/phoenix2014/phoenix-2014-videos.zip
  train: ../../data/phoenix2014/phoenix2014.train
  dev: ../../data/phoenix2014/phoenix2014.dev
  test: ../../data/phoenix2014/phoenix2014.test
  train_sgn_features: ../CSLR/results/phoenix-2014_ISLR/prediction_slide/train/train_features.pkl
  dev_sgn_features: ../CSLR/results/phoenix-2014_ISLR/prediction_slide/dev/dev_features.pkl
  test_sgn_features: ../CSLR/results/phoenix-2014_ISLR/prediction_slide/test/test_features.pkl
  dataset_name: phoenix2014
  level: word #word or char
  txt_lowercase: true
  max_sent_length: 400  #100
  transform_cfg:
    img_size: 224
    color_jitter: true
    bottom_area: 0.7 
    center_crop_size: 224 
    center_crop: False
    randomcrop_threshold: 1
    aspect_ratio_min: 0.75
    aspect_ratio_max: 1.3
    temporal_augmentation:
      tmin: 0.5
      tmax: 1.5
  fea_sample: avgpool
testing:
  cfg:
    recognition:
      beam_size: 5
training:
  load_ckpt: results/phoenix-2014_s2g/ckpts/best.ckpt
  overwrite: True
  model_dir: results/phoenix-2014_fuse_online
  random_seed: 321
  shuffle: True
  num_workers: 4
  batch_size: 1 
  total_epoch: 40
  keep_last_ckpts: 1
  validation: 
    unit: epoch
    freq: 1
    cfg:
      recognition:
        beam_size: 5
  optimization:
    optimizer: Adam
    learning_rate:
      default: 1.0e-4
    weight_decay: 0.001
    betas:
    - 0.9
    - 0.998
    scheduler: cosineannealing
    t_max: 40
model:
  RecognitionNetwork:
    GlossTokenizer:
      lower_case: False
      gloss2id_file: ../../data/phoenix2014/phoenix2014_gloss2ids0.pkl
    s3d:
      pretrained_ckpt: ../../pretrained_models/s3ds_actioncls_ckpt #from K400
      use_block: 4
      freeze_block: 1
    keypoint_s3d:
      in_channel: 0 # placeholder
      pretrained_ckpt: ../../pretrained_models/s3ds_actioncls_ckpt #from K400
      use_block: 4
      freeze_block: 0
    heatmap_cfg:
      raw_size:
        - 260
        - 210 
      input_size: 112
      sigma: 8
    fuse_method: triplehead_cat_bilateral
    lateral:
      pose2rgb: true
      rgb2pose: true
      variant_pose2rgb: null
      variant_rgb2pose: null
      fusion_features:
        - c1
        - c2
        - c3
    pyramid:
      version: v1
      rgb: multi_head
      pose: multi_head
      head_weight_rgb: 0.2
      head_weight_keypoint: 0.5
      num_levels: 3
    visual_head:
      input_size: 832
      hidden_size: 512
      ff_size: 2048
      pe: True 
      ff_kernelsize:
        - 3
        - 3
      adapter: freeze_backbone_aux_head
    cross_distillation:
      teacher_detach: True
      types:
        ensemble_last_teaches_keypoint: 1
        ensemble_last_teaches_rgb: 1
        ensemble_last_teaches_fuse: 1
    slide_fea_weight: 0.5