task: ISLR
data:
  input_data: videos #features, gloss
  input_streams:
    - keypoint
    - rgb
  keypoint_file: ../../data/csl-daily/keypoints_hrnet_dark_coco_wholebody_iso.pkl
  use_keypoints:
    - pose
    - mouth_half
    - hand
  zip_file: ../../data/csl-daily/sentence_frames-512x512.zip
  train: ../../data/csl-daily/csl.train
  dev: ../../data/csl-daily/csl.dev
  test: ../../data/csl-daily/csl.test
  vocab_file: ../../data/csl-daily/csl_iso_with_blank.vocab
  dataset_name: csl
  level: word #word or char
  txt_lowercase: true
  num_output_frames: -1  #to-debug
  win_size: 16
  stride: 1
  split_size: 24
  prob_thr: 
    - -1
  max_sent_length: 400
  transform_cfg:
    img_size: 224
    color_jitter: true
    bottom_area: 0.7 #to-do
    csl_cut: False
    csl_resize: 
      - 320
      - 320
    center_crop_size: 270 #to-change for csl
    center_crop: true
    randomcrop_threshold: 1
    aspect_ratio_min: 0.75
    aspect_ratio_max: 1.3
    temporal_augmentation:  #deprecated for ISLR
      tmin: 0.5
      tmax: 1.5
testing:
  cfg:
    recognition:
      beam_size: 10
training:
  overwrite: true
  model_dir: results/csl-daily_ISLR
  random_seed: 321
  shuffle: True
  num_workers: 8
  batch_size: 1 #to-debug!
  total_epoch: 100
  keep_last_ckpts: 5
  validation: 
    unit: epoch
    freq: 1
    cfg:
      recognition:
        beam_size: 1
  optimization:
    optimizer: Adam
    learning_rate:
      default: 1.0e-4
    weight_decay: 0.001
    betas:
    - 0.9
    - 0.998
    scheduler: cosineannealing
    t_max: 100
model:
  RecognitionNetwork:
    GlossTokenizer:
      gloss2id_file: ../../pretrained_models/mBart_de_2/gloss2ids.pkl
    s3d:
      pretrained_ckpt: ../../pretrained_models/s3ds_actioncls_ckpt #from K400
      use_block: 5
      freeze_block: 0
    keypoint_s3d:
      in_channel: 0 # placeholder
      pretrained_ckpt: ../../pretrained_models/s3ds_actioncls_ckpt #from K400
      use_block: 5
      freeze_block: 0
    heatmap_cfg:
      raw_size:
        - 512
        - 512 #associated with name2keypoint file
      map_size:
        - 170
        - 170
      input_size: 112
      sigma: 8
      # threshold: 0.5
    fuse_method: triplehead_cat_bilateral
    lateral:
      pose2rgb: true
      rgb2pose: true
      variant_pose2rgb: null
      variant_rgb2pose: null
      interpolate: false
      kernel_size: 
        - 1
        - 3
        - 3
      fusion_features:
        - c1
        - c2
        - c3
        - c4
    pyramid:
      version: v1
      rgb: null
      pose: null
    aux_head:
      head_weight_rgb: 0.2
      head_weight_keypoint: 0.5
      num: 0
    visual_head:
      variant: sep_conv
      use_extra_linear: false  #for joint head only
      input_size: 1024
      hidden_size: 512  #deprecated
      ff_size: 2048  #deprecated
      pe: True  #deprecated
      ff_kernelsize:  #deprecated
        - 3
        - 3
      word_emb_dim: 300
      temp: 0.1
      contras_setting: null
      topk: 1115
      # split_setting: split_att_gaussian_ext_linear_keepscale
    label_smooth: 0.2
